
    drop table user if exists;

    create table user (
        id bigint generated by default as identity,
        create_time timestamp,
        email varchar(255),
        login_name varchar(255) not null unique,
        name varchar(255),
        plain_password varchar(255),
        sha_password varchar(255),
        status varchar(255),
        primary key (id)
    );

    CREATE SEQUENCE SEQ_USER START WITH 100 INCREMENT BY 1;

insert into user (create_time, email, login_name, name, plain_password, sha_password, status,id) values (sysdate, 'test@ffcs.cn', 'admin1', 'admin', '123456', 'abc', 'enabled',SEQ_USER.NEXTVAL);
insert into user (create_time, email, login_name, name, plain_password, sha_password, status,id) values (sysdate, 'test@ffcs.cn', 'admin2', 'admin', '123456', 'abc', 'enabled',SEQ_USER.NEXTVAL);
insert into user (create_time, email, login_name, name, plain_password, sha_password, status,id) values (sysdate, 'test@ffcs.cn', 'admin3', 'admin', '123456', 'abc', 'enabled',SEQ_USER.NEXTVAL);
insert into user (create_time, email, login_name, name, plain_password, sha_password, status,id) values (sysdate, 'test@ffcs.cn', 'admin4', 'admin', '123456', 'abc', 'enabled',SEQ_USER.NEXTVAL);
insert into user (create_time, email, login_name, name, plain_password, sha_password, status,id) values (sysdate, 'test@ffcs.cn', 'admin5', 'admin', '123456', 'abc', 'enabled',SEQ_USER.NEXTVAL);
insert into user (create_time, email, login_name, name, plain_password, sha_password, status,id) values (sysdate, 'test@ffcs.cn', 'admin6', 'admin', '123456', 'abc', 'disabled',SEQ_USER.NEXTVAL);
insert into user (create_time, email, login_name, name, plain_password, sha_password, status,id) values (sysdate, 'test@ffcs.cn', 'admin7', 'admin', '123456', 'abc', 'enabled',SEQ_USER.NEXTVAL);
insert into user (create_time, email, login_name, name, plain_password, sha_password, status,id) values (sysdate, 'test@ffcs.cn', 'admin8', 'admin', '123456', 'abc', 'enabled',SEQ_USER.NEXTVAL);
insert into user (create_time, email, login_name, name, plain_password, sha_password, status,id) values (sysdate, 'test@ffcs.cn', 'admin9', 'admin', '123456', 'abc', 'enabled',SEQ_USER.NEXTVAL);
insert into user (create_time, email, login_name, name, plain_password, sha_password, status,id) values (sysdate, 'test@ffcs.cn', 'admin10', 'admin', '123456', 'abc', 'enabled',SEQ_USER.NEXTVAL);
insert into user (create_time, email, login_name, name, plain_password, sha_password, status,id) values (sysdate, 'test@ffcs.cn', 'admin11', 'admin', '123456', 'abc', 'disabled',SEQ_USER.NEXTVAL);
insert into user (create_time, email, login_name, name, plain_password, sha_password, status,id) values (sysdate, 'test@ffcs.cn', 'admin12', 'admin', '123456', 'abc', 'enabled',SEQ_USER.NEXTVAL);
insert into user (create_time, email, login_name, name, plain_password, sha_password, status,id) values (sysdate, 'test@ffcs.cn', 'admin13', 'admin', '123456', 'abc', 'enabled',SEQ_USER.NEXTVAL);
insert into user (create_time, email, login_name, name, plain_password, sha_password, status,id) values (sysdate, 'test@ffcs.cn', 'admin14', 'admin', '123456', 'abc', 'disabled',SEQ_USER.NEXTVAL);
insert into user (create_time, email, login_name, name, plain_password, sha_password, status,id) values (sysdate, 'test@ffcs.cn', 'admin15', 'admin', '123456', 'abc', 'disabled',SEQ_USER.NEXTVAL);
insert into user (create_time, email, login_name, name, plain_password, sha_password, status,id) values (sysdate, 'test@ffcs.cn', 'admin16', 'admin', '123456', 'abc', 'disabled',SEQ_USER.NEXTVAL);
insert into user (create_time, email, login_name, name, plain_password, sha_password, status,id) values (sysdate, 'test@ffcs.cn', 'admin17', 'admin', '123456', 'abc', 'enabled',SEQ_USER.NEXTVAL);
insert into user (create_time, email, login_name, name, plain_password, sha_password, status,id) values (sysdate, 'test@ffcs.cn', 'admin18', 'admin', '123456', 'abc', 'disabled',SEQ_USER.NEXTVAL);
insert into user (create_time, email, login_name, name, plain_password, sha_password, status,id) values (sysdate, 'test@ffcs.cn', 'admin19', 'admin', '123456', 'abc', 'disabled',SEQ_USER.NEXTVAL);
insert into user (create_time, email, login_name, name, plain_password, sha_password, status,id) values (sysdate, 'test@ffcs.cn', 'admin20', 'admin', '123456', 'abc', 'enabled',SEQ_USER.NEXTVAL);